# Site settings
url: https://lufevida.github.io
baseurl: /html5up-big-picture
title: Big Picture
author: HTML5 UP
introTitle: Intro
sectionOneTitle: What I Do
sectionTwoTitle: Who I Am
sectionThreeTitle: My Work

# Contact information